name: Prettify Code

on: [push, pull_request]

jobs:
  prettify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # Disable automatic token persistence

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Adjust the version as needed

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust the version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black
          npm install

      - name: Run format script
        run: |
          chmod +x ./code/dev_tools/format.sh
          ./code/dev_tools/format.sh

      - name: Check for changes
        id: git_status
        run: |
          git diff --exit-code || echo "has_changes=true" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.has_changes == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Prettify code'
          git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git
        env:
          PAT: ${{ secrets.PAT }}
